// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/58b1706b11c3c5ae08fe22a0534a5f2f1215423e/immutability-helper/immutability-helper.d.ts
declare module "immutability-helper" {
  interface UpdateSpecCommand {
    $set?: any;
    $merge?: {};
    $apply?(value: any): any;
    [customCommand: string]: any;
  }

  interface UpdateSpecPath {
    [pathPart: string]: UpdateSpec;
  }

  type UpdateSpec = UpdateSpecCommand | UpdateSpecPath;

  interface UpdateArraySpec extends UpdateSpecCommand {
    $push?: any[];
    $unshift?: any[];
    $splice?: any[][];
    [customCommand: string]: any;
  }

  type CommandHandler = (specValue: any, originalValue: any) => any;

  interface UpdateFunction {
    (value: any[], spec: UpdateArraySpec): any[];
    (value: {}, spec: UpdateSpec): any;
    extend: (commandName: string, handler: CommandHandler) => any;
  }

  interface Update extends UpdateFunction {
    newContext(): UpdateFunction;
  }

  const update: Update;
  export = update;
}
