// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/react-router-bootstrap/react-router-bootstrap.d.ts
declare namespace ReactRouterBootstrap {
    // Import React
    import React = __React;

    interface LinkContainerProps extends ReactRouter.LinkProps {
        disabled?: boolean
    }
    interface LinkContainer extends React.ComponentClass<LinkContainerProps> {}
    interface LinkContainerElement extends React.ReactElement<LinkContainerProps> {}
    const LinkContainer: LinkContainer

    const IndexLinkContainer: LinkContainer
}

declare module "react-router-bootstrap/lib/LinkContainer" {

    export default ReactRouterBootstrap.LinkContainer

}

declare module "react-router-bootstrap/lib/IndexLinkContainer" {

    export default ReactRouterBootstrap.IndexLinkContainer

}

declare module "react-router-bootstrap" {

    import LinkContainer from "react-router-bootstrap/lib/LinkContainer"
    
    import IndexLinkContainer from "react-router-bootstrap/lib/IndexLinkContainer"

    export {
        LinkContainer,
        IndexLinkContainer
    }

}
