// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a11d013885ea072e6dba017ec5181eaf1ee152db/react-modal/react-modal.d.ts
declare module "react-modal" {
    interface ReactModal {
        isOpen: boolean;
        style?: {
            content: {
                [key: string]: any;
            },
            overlay: {
                [key: string]: any;
            }
        },
        appElement?: HTMLElement | {},
        onAfterOpen?: Function,
        onRequestClose?: Function,
        closeTimeoutMS?: number,
        ariaHideApp?: boolean,
        shouldCloseOnOverlayClick?: boolean,
        overlayClassName?: string,
        className?: string
    }
    let ReactModal: __React.ClassicComponentClass<ReactModal>;
    export = ReactModal;
}
